# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCT03AlterarCliente():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cT03AlterarCliente(self):
    self.driver.get("http://localhost/html/view/AlterarCliente.html")
    self.driver.set_window_size(1936, 1066)
    assert self.driver.find_element(By.ID, "titulo").text == "Alterar Cliente"
    assert self.driver.find_element(By.CSS_SELECTOR, ".campo").text == "CPF\\\\n\\\\n\\\\nVoltar"
    elements = self.driver.find_elements(By.NAME, "ccpf")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".botao")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".botaoB")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "ccpf").click()
    self.driver.find_element(By.NAME, "ccpf").send_keys("111")
    self.driver.find_element(By.CSS_SELECTOR, ".botao").click()
    assert self.driver.find_element(By.ID, "titulo").text == "Confirme o cliente que você quer alterar"
    assert self.driver.find_element(By.CSS_SELECTOR, ".campo").text == "CPF Antigo\\\\n\\\\nNovo Nome\\\\n\\\\n\\\\nNovo Email\\\\n\\\\n\\\\nNova Senha\\\\n\\\\n\\\\nNovo CPF"
    assert self.driver.find_element(By.CSS_SELECTOR, ".campo").text == "CPF Antigo\\\\n\\\\nNovo Nome\\\\n\\\\n\\\\nNovo Email\\\\n\\\\n\\\\nNova Senha\\\\n\\\\n\\\\nNovo CPF"
    assert self.driver.find_element(By.CSS_SELECTOR, ".campo").text == "CPF Antigo\\\\n\\\\nNovo Nome\\\\n\\\\n\\\\nNovo Email\\\\n\\\\n\\\\nNova Senha\\\\n\\\\n\\\\nNovo CPF"
    assert self.driver.find_element(By.CSS_SELECTOR, ".campo").text == "CPF Antigo\\\\n\\\\nNovo Nome\\\\n\\\\n\\\\nNovo Email\\\\n\\\\n\\\\nNova Senha\\\\n\\\\n\\\\nNovo CPF"
    assert self.driver.find_element(By.CSS_SELECTOR, ".campo").text == "CPF Antigo\\\\n\\\\nNovo Nome\\\\n\\\\n\\\\nNovo Email\\\\n\\\\n\\\\nNova Senha\\\\n\\\\n\\\\nNovo CPF"
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".botao")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".botaoB")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "cantigocpf")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "cnome")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "cemail")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "csenha")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "ccpf")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.NAME, "cnome").send_keys("text")
    self.driver.find_element(By.NAME, "cemail").click()
    self.driver.find_element(By.NAME, "cemail").send_keys("text@tx.com")
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.NAME, "csenha").send_keys("text")
    self.driver.find_element(By.NAME, "ccpf").click()
    self.driver.find_element(By.NAME, "ccpf").send_keys("1111")
    self.driver.find_element(By.CSS_SELECTOR, ".botao").click()
  
