# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCT01CadastrarCliente():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cT01CadastrarCliente(self):
    self.driver.get("http://localhost/html/view/CadastrarCliente.html")
    self.driver.set_window_size(1936, 1066)
    assert self.driver.find_element(By.ID, "titulo").text == "Cadastro de Cliente"
    assert self.driver.find_element(By.CSS_SELECTOR, ".campo").text == "Nome\\\\n\\\\n\\\\nEmail\\\\n\\\\n\\\\nSenha\\\\n\\\\n\\\\nCPF\\\\n\\\\n\\\\nVoltar"
    assert self.driver.find_element(By.CSS_SELECTOR, ".campo").text == "Nome\\\\n\\\\n\\\\nEmail\\\\n\\\\n\\\\nSenha\\\\n\\\\n\\\\nCPF\\\\n\\\\n\\\\nVoltar"
    assert self.driver.find_element(By.CSS_SELECTOR, ".campo").text == "Nome\\\\n\\\\n\\\\nEmail\\\\n\\\\n\\\\nSenha\\\\n\\\\n\\\\nCPF\\\\n\\\\n\\\\nVoltar"
    assert self.driver.find_element(By.CSS_SELECTOR, ".campo").text == "Nome\\\\n\\\\n\\\\nEmail\\\\n\\\\n\\\\nSenha\\\\n\\\\n\\\\nCPF\\\\n\\\\n\\\\nVoltar"
    elements = self.driver.find_elements(By.NAME, "cnome")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "cemail").click()
    elements = self.driver.find_elements(By.NAME, "cemail")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "ccpf")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "csenha")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".botao")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".botaoB")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "cnome").click()
    self.driver.find_element(By.NAME, "cnome").send_keys("Teste")
    self.driver.find_element(By.NAME, "cemail").click()
    self.driver.find_element(By.NAME, "cemail").send_keys("teste@tx.com")
    self.driver.find_element(By.NAME, "csenha").click()
    self.driver.find_element(By.NAME, "csenha").send_keys("teste")
    self.driver.find_element(By.NAME, "ccpf").click()
    self.driver.find_element(By.NAME, "ccpf").send_keys("111")
    self.driver.find_element(By.CSS_SELECTOR, ".botao").click()
  
